const Definitions = {
    acne: [
        { ingredient: 'Azelaic acid', description: 'We nominate azelaic acid Best New Artist of 2019. Made from rye and barley, azelaic acid can do it all. She’s an acne expert - she’s anti-inflammatory, she prevents skin build up that clogs pores, and gets rid of the harmful bacteria (called P.acnes) that causes acne. Azelaic acid also stops rosacea in its tracks, combats dark spots and uneven skin tone, and encourages cell turnover so your skin heals more quickly and doesn’t scar. Azelaic acid is out here taking names and cashing checks, just like you! You approach life and all pursuits passionately. You’re all about exploration, whether that means going on adventures, delving deeper into your creativity, or self-exploration and learning more about yourself. Because of this, you easily attract friends and admirers who love the unique way that you move through life. Use azelaic acid as an acne treatment, an exfoliator, a hyperpigmentation-fighter, a problem-solver, to pay your credit card bill and clear your name.' },
        { ingredient: 'Niacinamide', description: 'Niacinamide won the Lifetime Achievement Award at the Grammys this year. Niacinamide, a form of Vitamin B, can and has done it all. She acts as an antioxidant and scavenges free radicals that damage skin. She improves moisture retention and restores your skin barrier by encouraging your skin to produce more ceramides. She keeps zits at bay by reducing inflammation and sebum production. Niacinamide also targets dark spots and uneven skin tone by preventing the transfer of excess melanin to the top layers of your skin. Niacinamide is out here taking names and cashing checks, just like you! You approach life and all pursuits passionately. You’re all about exploration, whether that means going on adventures, delving deeper into your creativity, or self-exploration and learning more about yourself. Because of this, you easily attract friends and admirers who love the unique way that you move through life. Use niacinamide as an acne treatment, an antioxidant, a hyperpigmentation-fighter, a problem-solver, to pay your credit card bill and clear your name.' },
    ],
    texture_scarring: [
        { ingredient: 'Vitamin C', description: 'Vitamin C is the Drake of skincare - an OG, everyone wants to feature it, multi-talented, a little bit unstable. Vitamin C is a potent antioxidant, meaning that it rids your skin of damaging free radicals from pollutants and UV-damage. It also fades dark spots and discoloration, and accelerates production of collagen to strengthen your skin and make it appear firmer and bouncier. Was Rihanna-Drake your favorite Drake? Similarly, Vitamin C does better paired with other ingredients like Vitamin E, kojic acid, and Centella Asiatica, and actually amps up the potency of these ingredients. You are also drawn to balancing and harmonious partnerships in your life. You care deeply about the happiness of your loved ones and aim to uplift them whenever possible; it’s what fulfills you. Trust yourself on your own too - you’re a pioneer with great ideas and intuition. Those qualities added to your natural charm make you unstoppable! Ideally use Vitamin C in its more stable forms (ascorbyl palmitate, magnesium ascorbyl phosphate/palmitate), or stabilized with Vitamin E/ferulic acid, to help fill in scars/texture, even your complexion, and generally come correct with Drake-at-the-beginning-and-end-of-the-decade-level attitude.' },
        { ingredient: 'Glucosamine', description: 'Glucosamine is a precursor of hyaluronic acid, meaning that your body is able to process it and turn it into hyaluronic acid. It’s also anti-inflammatory and can fade dark spots and scars by turning off tyrosinase (enzyme that controls melanin). This makes glucosamine great for accelerating wound healing, fading scars and texture, and keeping your skin looking juicy af. You keep it juicy juicy! Free-spirited, eccentric, an enigma - you laugh in the face of conventionality and prefer to pave your own way. You have a strong sense of conviction which can sometimes feed your stubbornness, but you just know what you want! Use glucosamine to help fill in scars and texture, and keep your skin strong and hydrated.' },
        { ingredient: 'Pyruvic acid', description: 'Pyruvic acid is an alpha-hydroxy acid (AHA) that comes from honey, apples, and/or fermented fruit. As an AHA, pyruvic acid is a great chemical exfoliator that also stimulates your skin’s production of collagen, elastin, and hyaluronic acid. It also has a larger molecule size which means that it doesn’t penetrate into your skin as deeply. If you have sensitive skin, this is great for you! This also makes pyruvic acid great for accelerating wound healing, fading scars and texture, and keeping your skin looking juicy af. You keep it juicy juicy! Free-spirited, eccentric, an enigma - you laugh in the face of conventionality and prefer to pave your own way. You have a strong sense of conviction which can sometimes feed your stubbornness, but you just know what you want! Use pyruvic acid to help fill in scars, smooth texture, and keep your skin strong and hydrated.' },
    ],
    eczema: [
        { ingredient: 'Ceramides', description: 'Ceramides are to your skin what Lil Nas X is to society: the glue that holds it all together. He brought together country and rap, and brought Billy Ray Cyrus out of retirement. Ceramides help to turn your skin into a water-tight seal to protect against TEWL (transepidermal water loss) and the invasion of harmful bacteria. They replenish your skin by bringing back moisture, and work well with all skin types and pretty much every other ingredient. You are also a unifier in your inner circle, the one that your friends/family couldn’t live without, hydrated, multitasking and multifaceted. Use ceramides for next-level hydration, restoration of that skin barrier, and keeping the haters (irritation, inflammation, eczema and psoriasis flare-ups) at bay. ' },
        { ingredient: 'Allantoin', description: 'Allantoin helps to heal wounds, soothe irritation, and stimulate skin cell turnover. She’s resilience, she’s renewal. She’s Kanye-born-again-Christian-post-MAGA-hat-level reinvention. You keep it pushing regardless, and that resilience is what helps you flourish! You are adaptable but stay deeply rooted in the values and support systems that ground you. Use allantoin alone or alongside humectants (hyaluronic acid, glycerin, honey) to soothe itchy, dry, or flaky skin and restore your skin’s barrier.' },
        { ingredient: 'Honey', description: 'Honey reduces inflammation, fends off bacteria, and acts as a soothing humectant by drawing water into your skin. It also feels thick and luxurious af in a cream or balm. You’re a nurturer - you keep your circle small and stay committed and loyal to the people you care about. You like to stay cozy - catch you under some blankets binge-watching reruns on Netflix. Winnie the Pooh might be your idol. Also maybe ASAP Mob. Use honey for deep hydration and to chill (your skin) tf out when inflammation, psoriasis, eczema, or rosacea come knocking.' },
    ],
    dry_skin: [
        { ingredient: 'Hyaluronic acid', description: 'If Rihanna were a skin care ingredient, she might be hyaluronic acid. Hyaluronic acid is a humectant that retains 1000X its weight in moisture in the skin, reinforces the skin’s barrier to reduce TEWL (transepidermal water loss) and protect from harmful bacteria, reduces the appearance of wrinkles, heals wounds by regulating inflammation levels, and acts like an antioxidant to scavenge free radicals. Hyaluronic acid is also compatible with all skin types because it occurs naturally in the framework of everyone’s skin! That might be why it seems like she’s in everything -  moisturizers, serums, makeup, fashion, music…wait are we still talking about Rihanna? You are effortlessly adaptable; you’ve absorbed every hard and wonderful lesson thrown your way which has made you Rihanna-level intuitive, empathetic, and magical. You’re invigorated by beautiful things, whether they’re experiences, art, people, or personalities. Use hyaluronic acid as a multitasking humectant to accompany your favorite moisturizer.' },
        { ingredient: 'Lactic acid', description: 'Lactic acid works in levels - at higher concentrations it is a particularly gentle AHA that loosens the bonds between surface-level skin cells, which helps to promote cell turnover and reveal younger, fresher skin underneath. At lower concentrations, it encourages your skin to increase its own production of ceramides and collagen, and acts as a humectant to increase water retention. You’re a gem at all different concentrations too! This is because you are Billie Eilish’s hair-level multifaceted. You juggle a mixture of friends and interests, and change your Tinder bio often. You’re quick-witted, curious, and passionate about a lot of different things. Use lactic acid to perk up dry, sensitive skin and get those rough patches feeling as soft as heartbroken-Drake lyrics.' },
        { ingredient: 'Shea butter', description: 'Do you follow Lizzo on Instagram? (If not, please pause and go do so immediately). Okay, now do you see how soft her butt looks? She’s probably using shea butter. Shea butter is an incredibly good emollient, meaning that it moistens and softens the skin. When your skin is dry, your skin cells don’t move together as a unit - they’re more rigid and allow things to slip through the cracks. Emollients like shea butter, make your skin barrier more flexible and therefore better at keeping moisture in and bacteria out. Shea butter also acts as a humectant to draw more water into the skin. Similar to shea butter and to Lizzo, you are also soft and 100% that B***h. You are nurturing, protective, and loving to those closest to you. While equal parts fierce and gentle, you are always very good at making others feel comfortable. Use shea butter as a part of your moisturization routine to butter up your dryest patches.' },
    ],
    redness_rosacea: [
        { ingredient: 'Centella Asiatica', description: 'Centella Asiatica, sometimes called “cica,” is the source of 4 major skincare compounds (madecassoside, asiaticoside, asiatic acid, madecassic acid) It’s multi-talented, which is why it’s having a real moment right now, particularly in Korean and Chinese skincare. Cica soothes inflammation, promotes wound healing, and encourages your skin to make more collagen and hyaluronic acid. This means that it fortifies your skin’s barrier to reduce redness, smooth, heal, hydrate, and promote glow. Because it’s so soothing, it’s particularly good for sensitive or inflamed skin. Just like cica, you’re also having your moment in the sun! You’re geographically, spiritually, and creatively adventurous. You light up every room with laughter and have a great sense of humor - it’s part of why your friends love you. You also have many talents, and are special because of your adaptability. Use Centella Asiatica to help calm redness and/or rosacea, soothe inflammation after a sunburn or breakout, and generally chill tf out.' },
        { ingredient: 'Green Tea Extract', description: 'Green tea extract is kind of the shit -- it’s been a major player in skincare for thousands of years in traditional Chinese medicine. It’s the source of several compounds that act as antioxidants to target free radicals caused by UV-damage, neutralize harmful bacteria, reduce inflammation, prevent the skin’s breakdown of collagen, and promote microcirculation in the skin. Good microcirculation helps the body transport nutrients to skin cells and flush out inflammatory molecules; bad microcirculation causes redness and rosacea. So, green tea extract translates to skin that is calmed, more elastic, more durable, and generally cute af. You know that you’re cute af and kind of the shit too! You’re a natural leader, and you have the ambition, determination, and bravery to back it up. You’re characterized by your resilience and strength. Your experiences always fortify you, making you into an even more courageous person. Use products formulated with green tea extract to help calm redness and/or rosacea, encourage firmer, stronger skin and self.' },
    ],
    bumpy_skin: [
        { ingredient: 'Glycolic Acid', description: 'Glycolic acid is an alpha-hydroxy acid (AHA) made from sugar cane, and its benefits are sweet af. It has the smallest molecule size of all the AHAs, meaning that it penetrates the skin very easily and more deeply than others. Glycolic acid exfoliates, and stimulates new cell generation and collagen production. So, glycolic acid pampers your skin by smoothing bumps and texture, strengthening the skin barrier, reducing scarring, brightening your complexion, and accelerating healing. Since your love language is self-care, this makes glycolic acid the Michelle to your Barack. You’re all about comfort and luxury, which is well-deserved since you’re also defined by your focus, ambition, and resilience. You’re a work hard, play hard type that others love because of your devotion. Use glycolic acid to exfoliate away any and all bumps and blemishes, evidence of past transgressions, and ragrets ;). ' }, 
        { ingredient: 'Bakuchiol', description: 'A staple in ancient Aruveydic medicine, bakuchiol, made from the babchi plant, is having a moment now as a plant-based retinol alternative. Why? It can increase collagen production and cell turnover rates as well as retinol can, but is gentler and less irritating than retinol.  It also has antioxidant and antibacterial abilities. This means that it’s super great for those with rosacea, psoriasis, eczema, and sensitive skin who still want baby’s butt-soft skin because it smoothes and soothes simultaneously. Plus, it’s naturally bright purple, making it cute and functional! Just like you! You’re a friend-favorite because of your kindness and supportiveness. You are uniquely attuned to how things work, and may work better together, and are good at offering guidance around this. You are both spiritual and practical, beautiful and hardworking. Use bakuchiol to smooth away your bumps, blemishes, questions, concerns, problems, and past transgressions. ' }, 
    ],
    psoriasis: [
        { ingredient: 'Urea', description: 'Urea gently exfoliates by sloughing off scaly and rough skin. It also acts as a humectant that prevents TEWL (transepidermal water loss) and encourages skin cell regeneration. Just like the layers that urea works its way through to reveal that fresh skin underneath, like real G’s you move in silence like lasagna. You’re plotting while everyone else is playing, two steps ahead until you pop out and surprise everyone like Beyonce did with Lemonade. Use urea as a potent moisturizer that will help reveal baby soft skin underneath even the roughest, dryest patches.' }, 
        { ingredient: 'Salicylic acid', description: 'This OG BHA made from willow bark has been around for a while and for good reason. It’s one of the best at unclogging every pore and loosening the bonds between skin cells for deep exfoliation. You’re a meticulous, hardworking, problem-solving legend too. You think critically about all things and put that mind to work - nothing gets past you. You’re a supportive friend who uses these smarts to help them out too. You might know salicylic acid as an acne-fighting type of B***h - and she’s great at that (particularly for blackheads and whiteheads) - but her exfoliating powers also help slough off rough and scaly eczema and psoriasis patches as well. What did we tell you? A true problem-solver! Accompany with a great moisturizer as salicylic acid can be drying. ' }, 
    ],
    dark_spots: [
        { ingredient: 'Tranexamic Acid', description: 'Tranexamic acid is a newer baby to the skincare world but she’s got a lot of potential. Tranexamic acid decreases melanocyte (skin cells that produce extra melanin) activity. This helps to fade dark spots, dark patches, and discoloration by calming down your hyperactive melanocytes only. We don’t support skin lightening over here. Tranexamic acid also regulates blood circulation to the skin. Have you ever experienced red/pink discoloration after a breakout? This condition, called post-inflammatory erythema (PIE), and melasma are both related to changes in blood circulation in the skin. This means that tranexamic acid helps combat these conditions as well. Black, red, brown - whatever color the spots you’re trying to tone down, tranexamic acid’s gotchu! You make people feel balanced and supported too! You’re attracted to harmony, and it’s what you provide to others too. You value your relationships and are dedicated to finding happiness both for yourself and others. You’re also a pioneer and thought leader - you pave the way in the things you’re passionate about. A legend!' }, 
        { ingredient: 'Licorice root', description: 'Licorice root is a great skincare ingredient because of its 2 major compounds, liquiritin and glabridin. Together, these compounds have heavy-hitting, hyperpigmentation-blasting benefits. In addition to its antioxidant and anti-inflammatory properties, licorice root fades discoloration and dark spots by turning off over-active tyrosinase (skin enzyme that controls your production of extra melanin). Poor licorice, long misunderstood as a gross candy when really we’re supposed to have been rubbing it on our faces this whole time! Sometimes you might feel a lil misunderstood too. You’re passionate, powerful, and intuitive person which can intimidate others. When people get to know you, they love you for your empathy, complexity, and ambition. You’re a bad B***h and everyone who knows you, knows it. Use licorice root to fade the most stubborn dark spots that have been giving you a hard time.' }, 
        { ingredient: 'Alpha-arbutin', description: 'Sweet alpha-arbutin is derived from bearberries, cranberries, blueberries, and/or pears, and combats dark spots and discoloration. It’s unique in that it slowly releases its active compounds over time - the full potential of its benefits are revealed later, like coming home drunk and realizing you saved that last slice of pizza :) This makes alpha-arbutin particularly great for folks with sensitive skin because it won’t shock your skin by going to work full-force right away. It inhibits over-active tyrosinase (enzyme that controls your skin’s production of extra melanin) and prevents melanosomes (densely packed pockets of melanin) from developing. You’re a little self-protective as well, and reveal your best and truest self after some TLC - that’s when friends really get to see your gentle, compassionate, magical self. You’re capable of loving and committing to loved ones in a way they’ve probably rarely experienced - folks just have to stick around to be able to tap it. Use alpha-arbutin to combat sun damage, fade dark scars, and help build your best self in stealth mode.' }, 
    ],
    wrinkles: [
        { ingredient: 'Retinol', description: 'Retinol’s yearbook quote was, “Here for a good time, not a long time.”  Do you sometimes wish you could go back to last week or last year and not swipe right or drunk-buy that thing on Amazon? Retinol can at least help you look like you did. Made from Vitamin A, retinol smoothes wrinkles by increasing your skin’s production of collagen and encouraging cell turnover. By increasing cell turnover, retinol can also help unclog pores, exfoliate, and fade dark spots. She’s a real powerful, time-machine type of b***h. You look forward and onward also, and have ambition and determination like no other. You’re headstrong, stubborn, and destined for greatness. Failure? Who’s he? He could be walking down the street, you wouldn’t know a thing. Sorry to this man. You shine bright and approach all things with courage and optimism no matter what past regrets or mistakes. Use retinol to smooth texture and lines, fade discoloration, and achieve that perfect balance of self-denial.' }
    ]
}

export default Definitions;